url: https://lab.noesya.coop
title: Lab Noesya
subdomain: Lab
lang: fr

theme: jekyll-theme-noesya
options:
  menu_burger: true
  notes: true
  hover_navigation_links: true
  no_js: false

defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "categories"
    values:
      layout: "category"
  -
    scope:
      path: ""
      type: "years"
    values:
      layout: "year"


collections:
  pages:
    output: true
  posts:
    output: true
    permalink: /:year/:title
  rules:
    output: false
  categories:
    output: true
    permalink: /:title
  years:
    output: true
    permalink: /:title

plugins:
  - jekyll-minifier
  - jekyll-sitemap

sass:
  style: compressed
  load_paths:
      - _sass
      - node_modules

jekyll-minifier:
  remove_spaces_inside_tags: true
  remove_multi_spaces: true
  remove_intertag_spaces: true
  remove_comments: true
  compress_css: false
  compress_javascript: true

picture:
  ignore_missing_images: true
